#include "EchoesMMO.h"

DEFINE_LOG_CATEGORY(LogEchoesMMO);
DEFINE_LOG_CATEGORY(LogCombat);
DEFINE_LOG_CATEGORY(LogNetwork);

IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, EchoesMMO, "EchoesMMO");
